/*
 * This file was automatically generated by EvoSuite
 * Sat May 25 21:47:03 GMT 2019
 */

package com.wrapper.spotify.exceptions.detailed;

import org.junit.Test;
import static org.junit.Assert.*;
import com.wrapper.spotify.exceptions.detailed.BadRequestException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BadRequestException_ESTest extends BadRequestException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BadRequestException badRequestException0 = new BadRequestException();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      BadRequestException badRequestException0 = new BadRequestException("DcQ_");
      BadRequestException badRequestException1 = new BadRequestException("DcQ_", badRequestException0);
      assertFalse(badRequestException1.equals((Object)badRequestException0));
  }
}
