/*
 * This file was automatically generated by EvoSuite
 * Sat May 25 22:28:03 GMT 2019
 */

package com.wrapper.spotify.enums;

import org.junit.Test;
import static org.junit.Assert.*;
import com.wrapper.spotify.enums.ModelObjectType;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ModelObjectType_ESTest extends ModelObjectType_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ModelObjectType[] modelObjectTypeArray0 = ModelObjectType.values();
      assertEquals(7, modelObjectTypeArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ModelObjectType modelObjectType0 = ModelObjectType.valueOf("AUDIO_FEATURES");
      assertEquals("audio_features", modelObjectType0.getType());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ModelObjectType modelObjectType0 = ModelObjectType.keyOf("user");
      assertEquals("user", modelObjectType0.getType());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ModelObjectType modelObjectType0 = ModelObjectType.ARTIST;
      String string0 = modelObjectType0.getType();
      assertEquals("artist", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ModelObjectType.keyOf("");
  }
}
