/*
 * This file was automatically generated by EvoSuite
 * Sat May 25 22:59:05 GMT 2019
 */

package com.wrapper.spotify.enums;

import org.junit.Test;
import static org.junit.Assert.*;
import com.wrapper.spotify.enums.ProductType;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ProductType_ESTest extends ProductType_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ProductType[] productTypeArray0 = ProductType.values();
      assertEquals(5, productTypeArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ProductType productType0 = ProductType.valueOf("FREE");
      assertEquals("free", productType0.getType());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ProductType productType0 = ProductType.keyOf("premium");
      assertEquals(ProductType.PREMIUM, productType0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ProductType productType0 = ProductType.BASIC_DESKTOP;
      String string0 = productType0.getType();
      assertEquals("basic-desktop", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ProductType.keyOf("");
  }
}
