/*
 * This file was automatically generated by EvoSuite
 * Sat May 25 21:11:55 GMT 2019
 */

package com.wrapper.spotify.model_objects.specification;

import org.junit.Test;
import static org.junit.Assert.*;
import com.google.gson.JsonObject;
import com.wrapper.spotify.model_objects.specification.ExternalId;
import java.util.HashMap;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ExternalId_ESTest extends ExternalId_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ExternalId.Builder externalId_Builder0 = new ExternalId.Builder();
      ExternalId externalId0 = externalId_Builder0.build();
      Map<String, String> map0 = externalId0.getExternalIds();
      assertNull(map0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ExternalId.Builder externalId_Builder0 = new ExternalId.Builder();
      HashMap<String, String> hashMap0 = new HashMap<String, String>();
      externalId_Builder0.setExternalIds(hashMap0);
      ExternalId externalId0 = externalId_Builder0.build();
      Map<String, String> map0 = externalId0.getExternalIds();
      assertEquals(0, map0.size());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ExternalId.Builder externalId_Builder0 = new ExternalId.Builder();
      HashMap<String, String> hashMap0 = new HashMap<String, String>();
      externalId_Builder0.setExternalIds(hashMap0);
      ExternalId externalId0 = externalId_Builder0.build();
      hashMap0.put("com.wrapper.spotify.model_objects.specification.ExternalId", "com.wrapper.spotify.model_objects.specification.ExternalId");
      Map<String, String> map0 = externalId0.getExternalIds();
      assertFalse(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ExternalId.JsonUtil externalId_JsonUtil0 = new ExternalId.JsonUtil();
      ExternalId externalId0 = externalId_JsonUtil0.createModelObject((JsonObject) null);
      assertNull(externalId0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ExternalId.JsonUtil externalId_JsonUtil0 = new ExternalId.JsonUtil();
      JsonObject jsonObject0 = new JsonObject();
      ExternalId externalId0 = externalId_JsonUtil0.createModelObject(jsonObject0);
      ExternalId.Builder externalId_Builder0 = externalId0.builder();
      assertNotNull(externalId_Builder0);
  }
}
