/*
 * This file was automatically generated by EvoSuite
 * Sat May 25 20:08:11 GMT 2019
 */

package com.wrapper.spotify;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.wrapper.spotify.SpotifyHttpManager;
import java.net.InetAddress;
import java.net.URI;
import org.apache.http.HttpHost;
import org.apache.http.auth.UsernamePasswordCredentials;
import org.apache.http.entity.BasicHttpEntity;
import org.apache.http.entity.SerializableEntity;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockInetAddress;
import org.evosuite.runtime.mock.java.net.MockURI;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SpotifyHttpManager_ESTest extends SpotifyHttpManager_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      URI uRI0 = SpotifyHttpManager.makeUri("?0t&W2vMu%H\"<5");
      assertNull(uRI0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      URI uRI0 = SpotifyHttpManager.makeUri("U:jo%25(9g,a,+:z#U:jo%25(9g,a,+:z");
      assertNull(uRI0.getHost());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      URI uRI0 = SpotifyHttpManager.makeUri("http://http@http:1274?http#http");
      assertEquals("http", uRI0.getRawUserInfo());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SpotifyHttpManager.Builder spotifyHttpManager_Builder0 = new SpotifyHttpManager.Builder();
      Integer integer0 = new Integer(0);
      SpotifyHttpManager.Builder spotifyHttpManager_Builder1 = spotifyHttpManager_Builder0.setSocketTimeout(integer0);
      // Undeclared exception!
      spotifyHttpManager_Builder1.build();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SpotifyHttpManager.Builder spotifyHttpManager_Builder0 = new SpotifyHttpManager.Builder();
      Integer integer0 = new Integer((-3508));
      spotifyHttpManager_Builder0.setSocketTimeout(integer0);
      // Undeclared exception!
      spotifyHttpManager_Builder0.build();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SpotifyHttpManager.Builder spotifyHttpManager_Builder0 = new SpotifyHttpManager.Builder();
      Integer integer0 = new Integer(2442);
      spotifyHttpManager_Builder0.setSocketTimeout(integer0);
      // Undeclared exception!
      spotifyHttpManager_Builder0.build();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SpotifyHttpManager.Builder spotifyHttpManager_Builder0 = new SpotifyHttpManager.Builder();
      UsernamePasswordCredentials usernamePasswordCredentials0 = new UsernamePasswordCredentials("kOYB.igOA4-(", "kOYB.igOA4-(");
      SpotifyHttpManager.Builder spotifyHttpManager_Builder1 = spotifyHttpManager_Builder0.setProxyCredentials(usernamePasswordCredentials0);
      // Undeclared exception!
      spotifyHttpManager_Builder1.build();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SpotifyHttpManager.Builder spotifyHttpManager_Builder0 = new SpotifyHttpManager.Builder();
      UsernamePasswordCredentials usernamePasswordCredentials0 = new UsernamePasswordCredentials("p3bOAmJEL)s^gl[:nR", "p3bOAmJEL)s^gl[:nR");
      HttpHost httpHost0 = new HttpHost("p3bOAmJEL)s^gl[:nR", 0);
      spotifyHttpManager_Builder0.setProxy(httpHost0);
      spotifyHttpManager_Builder0.setProxyCredentials(usernamePasswordCredentials0);
      // Undeclared exception!
      spotifyHttpManager_Builder0.build();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SpotifyHttpManager.Builder spotifyHttpManager_Builder0 = new SpotifyHttpManager.Builder();
      HttpHost httpHost0 = new HttpHost("Q+gsb&7\"uu}Kj", 475);
      SpotifyHttpManager.Builder spotifyHttpManager_Builder1 = spotifyHttpManager_Builder0.setProxy(httpHost0);
      UsernamePasswordCredentials usernamePasswordCredentials0 = new UsernamePasswordCredentials("http", "Q+gsb&7\"uu}Kj");
      spotifyHttpManager_Builder1.setProxyCredentials(usernamePasswordCredentials0);
      // Undeclared exception!
      spotifyHttpManager_Builder1.build();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SpotifyHttpManager.Builder spotifyHttpManager_Builder0 = new SpotifyHttpManager.Builder();
      UsernamePasswordCredentials usernamePasswordCredentials0 = new UsernamePasswordCredentials("kOYB.igOA4-(", "kOYB.igOA4-(");
      SpotifyHttpManager.Builder spotifyHttpManager_Builder1 = spotifyHttpManager_Builder0.setProxyCredentials(usernamePasswordCredentials0);
      HttpHost httpHost0 = new HttpHost("^?kb7;B");
      SpotifyHttpManager.Builder spotifyHttpManager_Builder2 = spotifyHttpManager_Builder1.setProxy(httpHost0);
      // Undeclared exception!
      spotifyHttpManager_Builder2.build();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SpotifyHttpManager.Builder spotifyHttpManager_Builder0 = new SpotifyHttpManager.Builder();
      Integer integer0 = new Integer(0);
      SpotifyHttpManager.Builder spotifyHttpManager_Builder1 = spotifyHttpManager_Builder0.setConnectionRequestTimeout(integer0);
      // Undeclared exception!
      spotifyHttpManager_Builder1.build();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SpotifyHttpManager.Builder spotifyHttpManager_Builder0 = new SpotifyHttpManager.Builder();
      Integer integer0 = new Integer((-393));
      SpotifyHttpManager.Builder spotifyHttpManager_Builder1 = spotifyHttpManager_Builder0.setConnectionRequestTimeout(integer0);
      // Undeclared exception!
      spotifyHttpManager_Builder1.build();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SpotifyHttpManager.Builder spotifyHttpManager_Builder0 = new SpotifyHttpManager.Builder();
      Integer integer0 = new Integer(904);
      spotifyHttpManager_Builder0.setConnectionRequestTimeout(integer0);
      // Undeclared exception!
      spotifyHttpManager_Builder0.build();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SpotifyHttpManager.Builder spotifyHttpManager_Builder0 = new SpotifyHttpManager.Builder();
      Integer integer0 = new Integer(990);
      SpotifyHttpManager.Builder spotifyHttpManager_Builder1 = spotifyHttpManager_Builder0.setConnectTimeout(integer0);
      // Undeclared exception!
      spotifyHttpManager_Builder1.build();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      SpotifyHttpManager.Builder spotifyHttpManager_Builder0 = new SpotifyHttpManager.Builder();
      Integer integer0 = new Integer(0);
      SpotifyHttpManager.Builder spotifyHttpManager_Builder1 = spotifyHttpManager_Builder0.setConnectTimeout(integer0);
      // Undeclared exception!
      spotifyHttpManager_Builder1.build();
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      SpotifyHttpManager.Builder spotifyHttpManager_Builder0 = new SpotifyHttpManager.Builder();
      Integer integer0 = Integer.valueOf((-2505));
      spotifyHttpManager_Builder0.setConnectTimeout(integer0);
      SpotifyHttpManager spotifyHttpManager0 = new SpotifyHttpManager(spotifyHttpManager_Builder0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      SpotifyHttpManager.Builder spotifyHttpManager_Builder0 = new SpotifyHttpManager.Builder();
      Integer integer0 = new Integer(0);
      spotifyHttpManager_Builder0.setCacheMaxObjectSize(integer0);
      // Undeclared exception!
      spotifyHttpManager_Builder0.build();
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      SpotifyHttpManager.Builder spotifyHttpManager_Builder0 = new SpotifyHttpManager.Builder();
      Integer integer0 = new Integer((-393));
      spotifyHttpManager_Builder0.setCacheMaxObjectSize(integer0);
      // Undeclared exception!
      spotifyHttpManager_Builder0.build();
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      SpotifyHttpManager.Builder spotifyHttpManager_Builder0 = new SpotifyHttpManager.Builder();
      Integer integer0 = new Integer(904);
      SpotifyHttpManager.Builder spotifyHttpManager_Builder1 = spotifyHttpManager_Builder0.setCacheMaxObjectSize(integer0);
      // Undeclared exception!
      spotifyHttpManager_Builder1.build();
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      SpotifyHttpManager.Builder spotifyHttpManager_Builder0 = new SpotifyHttpManager.Builder();
      Integer integer0 = new Integer(25);
      SpotifyHttpManager.Builder spotifyHttpManager_Builder1 = spotifyHttpManager_Builder0.setCacheMaxEntries(integer0);
      // Undeclared exception!
      spotifyHttpManager_Builder1.build();
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      SpotifyHttpManager.Builder spotifyHttpManager_Builder0 = new SpotifyHttpManager.Builder();
      Integer integer0 = new Integer(0);
      SpotifyHttpManager.Builder spotifyHttpManager_Builder1 = spotifyHttpManager_Builder0.setCacheMaxEntries(integer0);
      // Undeclared exception!
      spotifyHttpManager_Builder1.build();
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      SpotifyHttpManager.Builder spotifyHttpManager_Builder0 = new SpotifyHttpManager.Builder();
      Integer integer0 = new Integer((-459));
      spotifyHttpManager_Builder0.setCacheMaxEntries(integer0);
      // Undeclared exception!
      spotifyHttpManager_Builder0.build();
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      SpotifyHttpManager.Builder spotifyHttpManager_Builder0 = new SpotifyHttpManager.Builder();
      Integer integer0 = new Integer((-2));
      SpotifyHttpManager.Builder spotifyHttpManager_Builder1 = spotifyHttpManager_Builder0.setCacheMaxEntries(integer0);
      // Undeclared exception!
      spotifyHttpManager_Builder1.build();
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      SpotifyHttpManager.Builder spotifyHttpManager_Builder0 = new SpotifyHttpManager.Builder();
      // Undeclared exception!
      spotifyHttpManager_Builder0.build();
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      SpotifyHttpManager.Builder spotifyHttpManager_Builder0 = new SpotifyHttpManager.Builder();
      SpotifyHttpManager spotifyHttpManager0 = new SpotifyHttpManager(spotifyHttpManager_Builder0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      // Undeclared exception!
      try { 
        SpotifyHttpManager.makeUri((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      SpotifyHttpManager.Builder spotifyHttpManager_Builder0 = new SpotifyHttpManager.Builder();
      BasicHttpEntity basicHttpEntity0 = new BasicHttpEntity();
      // Undeclared exception!
      spotifyHttpManager_Builder0.build();
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      SpotifyHttpManager.Builder spotifyHttpManager_Builder0 = new SpotifyHttpManager.Builder();
      Integer integer0 = new Integer(0);
      spotifyHttpManager_Builder0.setCacheMaxObjectSize(integer0);
      SpotifyHttpManager spotifyHttpManager0 = new SpotifyHttpManager(spotifyHttpManager_Builder0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      SpotifyHttpManager.Builder spotifyHttpManager_Builder0 = new SpotifyHttpManager.Builder();
      Integer integer0 = new Integer(328);
      spotifyHttpManager_Builder0.setCacheMaxEntries(integer0);
      SpotifyHttpManager spotifyHttpManager0 = new SpotifyHttpManager(spotifyHttpManager_Builder0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      URI uRI0 = MockURI.create("http");
      MockURI.relativize(uRI0, uRI0);
      SerializableEntity serializableEntity0 = new SerializableEntity(uRI0);
      SpotifyHttpManager.Builder spotifyHttpManager_Builder0 = new SpotifyHttpManager.Builder();
      // Undeclared exception!
      spotifyHttpManager_Builder0.build();
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      SpotifyHttpManager.makeUri("");
      SpotifyHttpManager.Builder spotifyHttpManager_Builder0 = new SpotifyHttpManager.Builder();
      // Undeclared exception!
      spotifyHttpManager_Builder0.build();
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      SpotifyHttpManager.Builder spotifyHttpManager_Builder0 = new SpotifyHttpManager.Builder();
      Integer integer0 = new Integer(1274);
      spotifyHttpManager_Builder0.setSocketTimeout(integer0);
      SpotifyHttpManager spotifyHttpManager0 = new SpotifyHttpManager(spotifyHttpManager_Builder0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      SpotifyHttpManager.Builder spotifyHttpManager_Builder0 = new SpotifyHttpManager.Builder();
      InetAddress inetAddress0 = MockInetAddress.anyLocalAddress();
      HttpHost httpHost0 = new HttpHost(inetAddress0);
      SpotifyHttpManager.Builder spotifyHttpManager_Builder1 = spotifyHttpManager_Builder0.setProxy(httpHost0);
      SpotifyHttpManager spotifyHttpManager0 = null;
      try {
        spotifyHttpManager0 = new SpotifyHttpManager(spotifyHttpManager_Builder1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.concurrent.ConcurrentHashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      SpotifyHttpManager.Builder spotifyHttpManager_Builder0 = new SpotifyHttpManager.Builder();
      Integer integer0 = new Integer(1274);
      SpotifyHttpManager.Builder spotifyHttpManager_Builder1 = spotifyHttpManager_Builder0.setConnectionRequestTimeout(integer0);
      SpotifyHttpManager spotifyHttpManager0 = new SpotifyHttpManager(spotifyHttpManager_Builder1);
  }
}
